### ISSUE TITLE
大佬啥时候支持windows

### ISSUE THREAD

**Issue by loopsoftp** [jiejieTop/mqttclient#1]
想封装一个windows下的动态库

**Comment by jiejieTop** [comment]
暂时还没有这个计划哦，因为我比较少用Windows编程，因为代码开源，你也可以尝试移植，修改[ platform ](https://github.com/jiejieTop/mqttclient/tree/master/platform)的平台层，包括内存管理、线程、时间、互斥与同步、以及socket使用Windows平台的socket即可。
