### ISSUE TITLE
公网断开, 局域网内反复连接服务器

### ISSUE THREAD

**Issue by luzefeng123** [jiejieTop/mqttclient#10]
遇到个问题, 公网出现问题的时候, 无法正常连接到服务器上, 调试信息打印四次连接成功, 打印 rc 返回值, -4 
![image](https://user-images.githubusercontent.com/50038360/88549898-73176f00-d053-11ea-9207-cfe4d7067f5e.png)
屏蔽 exit: 后面的 if(rc == KAWAII_MQTT_SUCCESS_ERR) 可以正常创建线程, 通信正常
![image](https://user-images.githubusercontent.com/50038360/88550162-cee1f800-d053-11ea-861a-d16e59727996.png)

想问下屏蔽这句判断, 会对程序稳定性有影响吗?

**Comment by luzefeng123** [comment]
mqtt 服务器建在局域网内的一台主机上

**Comment by jiejieTop** [comment]
屏蔽那一句，感觉是出错了，你应该是在一开始就没连接成功，然后导致没有创建内部线程
