### ISSUE TITLE
MQTT+TLS证书校验失败

### ISSUE THREAD

**Issue by wangt201** [jiejieTop/mqttclient#12]
大佬你好，我在ubuntu上测试MQTT+TLS时，连接emqx平台一直失败，提示如下证书校验失败，地址、port、ca证书已经设置了。您有遇到过么？
（关闭掉tls，mqtt是好用的）
（main.c代码我是用mqtt生成工具生成的）

运行时的错误提示：
![image](https://user-images.githubusercontent.com/57788610/89490931-9de68d80-d7e0-11ea-909f-ac9e3dffc552.png)

alinx@ubuntu:~/work/ppp_sdk/mqtt/mqttclient-master/build/bin$ ./emqx 

[31m[E] >> /home/alinx/work/ppp_sdk/mqtt/mqttclient-master/network/nettype_tls.c:30 server_certificate_verify()... server_certificate_verify failed returned 0x0004

[31m[E] >> /home/alinx/work/ppp_sdk/mqtt/mqttclient-master/network/nettype_tls.c:149 nettype_tls_connect()...mbedtls handshake failed returned 0x0004

**Comment by jiejieTop** [comment]
可能是你的证书配置错误呢，你用mqtt.fx验证一下你的证书啥的

**Comment by ganggangl** [comment]
此问题我也遇到了，证书没问题的

**Comment by jiejieTop** [comment]
证书的格式是什么呢？

> 此问题我也遇到了，证书没问题的

**Comment by ganggangl** [comment]
@jiejieTop 这是百度的，各大平台的ca证书基本上都是一致的，我试了下mqtt.fx工具和mosquitto的库都是可以的，希望能帮助找到原因
`-----BEGIN CERTIFICATE-----
MIIDXzCCAkegAwIBAgILBAAAAAABIVhTCKIwDQYJKoZIhvcNAQELBQAwTDEgMB4G
A1UECxMXR2xvYmFsU2lnbiBSb290IENBIC0gUjMxEzARBgNVBAoTCkdsb2JhbFNp
Z24xEzARBgNVBAMTCkdsb2JhbFNpZ24wHhcNMDkwMzE4MTAwMDAwWhcNMjkwMzE4
MTAwMDAwWjBMMSAwHgYDVQQLExdHbG9iYWxTaWduIFJvb3QgQ0EgLSBSMzETMBEG
A1UEChMKR2xvYmFsU2lnbjETMBEGA1UEAxMKR2xvYmFsU2lnbjCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBAMwldpB5BngiFvXAg7aEyiie/QV2EcWtiHL8
RgJDx7KKnQRfJMsuS+FggkbhUqsMgUdwbN1k0ev1LKMPgj0MK66X17YUhhB5uzsT
gHeMCOFJ0mpiLx9e+pZo34knlTifBtc+ycsmWQ1z3rDI6SYOgxXG71uL0gRgykmm
KPZpO/bLyCiR5Z2KYVc3rHQU3HTgOu5yLy6c+9C7v/U9AOEGM+iCK65TpjoWc4zd
QQ4gOsC0p6Hpsk+QLjJg6VfLuQSSaGjlOCZgdbKfd/+RFO+uIEn8rUAVSNECMWEZ
XriX7613t2Saer9fwRPvm2L7DWzgVGkWqQPabumDk3F2xmmFghcCAwEAAaNCMEAw
DgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFI/wS3+o
LkUkrk1Q+mOai97i3Ru8MA0GCSqGSIb3DQEBCwUAA4IBAQBLQNvAUKr+yAzv95ZU
RUm7lgAJQayzE4aGKAczymvmdLm6AC2upArT9fHxD4q/c2dKg8dEe3jgr25sbwMp
jjM5RcOO5LlXbKr8EpbsU8Yt5CRsuZRj+9xTaGdWPoO4zzUhw8lo/s7awlOqzJCK
6fBdRoyV3XpYKBovHd7NADdBj+1EbddTKJd+82cEHhXXipa0095MJ6RMG3NzdvQX
mcIfeg7jLQitChws/zyrVQ4PkX4268NXSb7hLi18YIvDQVETI53O9zJrlAGomecs
Mx86OyXShkDOOyyGeMlhLxS67ttVb9+E7gUJTb0o2HLO02JQZR7rkpeDMdmztcpH
WD9f
-----END CERTIFICATE-----
`
