### ISSUE TITLE
重连段错误问题

### ISSUE THREAD

**Issue by ganggangl** [jiejieTop/mqttclient#13]
大佬，你好。我在测试重连时发现了一个小问题。在建立连接和线程的重连都会使mqtt_connect函数，此函数会调用mqtt_connect_with_results函数。在mqtt_connect_with_results中，含有内存被free 2次和多次申请内存的现象。
![image](https://user-images.githubusercontent.com/16084266/90307589-15679b80-df0a-11ea-996f-b140218c21f6.png)

**Comment by JTangtyx** [comment]
是的，这个问题我也发现了，断连后重联就会段错误，目前我是添加了c->mqtt_network = (network_t*) platform_memory_alloc(sizeof(network_t));这句解决，按照上面老哥说的，    c->mqtt_read_buf = (uint8_t*) platform_memory_alloc(c->mqtt_write_buf_size);
    c->mqtt_write_buf = (uint8_t*) platform_memory_alloc(c->mqtt_write_buf_size);这两个确实时重复申请了

**Comment by Mr-99** [comment]
老哥，重连确实有段错误问题，我也遇到到了，重连导致内存被非法访问

**Comment by Mr-99** [comment]
> 是的，这个问题我也发现了，断连后重联就会段错误，目前我是添加了c->mqtt_network = (network_t*) platform_memory_alloc(sizeof(network_t));这句解决，按照上面老哥说的， c->mqtt_read_buf = (uint8_t*) platform_memory_alloc(c->mqtt_write_buf_size);
> c->mqtt_write_buf = (uint8_t*) platform_memory_alloc(c->mqtt_write_buf_size);这两个确实时重复申请了

怎么解决的，老哥

**Comment by JTangtyx** [comment]
就按照上面说的修改就可以了

**Comment by ganggangl** [comment]
> 是的，这个问题我也发现了，断连后重联就会段错误，目前我是添加了c->mqtt_network = (network_t*) platform_memory_alloc(sizeof(network_t));这句解决，按照上面老哥说的， c->mqtt_read_buf = (uint8_t*) platform_memory_alloc(c->mqtt_write_buf_size);
> c->mqtt_write_buf = (uint8_t*) platform_memory_alloc(c->mqtt_write_buf_size);这两个确实时重复申请了

**Comment by ganggangl** [comment]
> 是的，这个问题我也发现了，断连后重联就会段错误，目前我是添加了c->mqtt_network = (network_t*) platform_memory_alloc(sizeof(network_t));这句解决，按照上面老哥说的， c->mqtt_read_buf = (uint8_t*) platform_memory_alloc(c->mqtt_write_buf_size);
> c->mqtt_write_buf = (uint8_t*) platform_memory_alloc(c->mqtt_write_buf_size);这两个确实时重复申请了

添加c->mqtt_network = (network_t*) platform_memory_alloc(sizeof(network_t));不如将重连失败释放的那两行注释调，加这一句相当于释放了，再申请。理由：假如一致重连失败，这个接口会在内置的线程里重复调用的。

**Comment by ganggangl** [comment]
> 大佬，你好。我在测试重连时发现了一个小问题。在建立连接和线程的重连都会使mqtt_connect函数，此函数会调用mqtt_connect_with_results函数。在mqtt_connect_with_results中，含有内存被free 2次和多次申请内存的现象。
> ![image](https://user-images.githubusercontent.com/16084266/90307589-15679b80-df0a-11ea-996f-b140218c21f6.png)

**Comment by Torchwoods** [comment]
![image](https://user-images.githubusercontent.com/6436021/92376088-a2ca9400-f134-11ea-8a59-55b5501755df.png)
c->mqtt_network在network_release里面被清零了，所以不用释放，直接屏蔽 platform_memory_free(c->mqtt_network)，添加c->mqtt_write_buf和c->mqtt_read_buf内存释放，就可以了

**Comment by ganggangl** [comment]
> ![image](https://user-images.githubusercontent.com/6436021/92376088-a2ca9400-f134-11ea-8a59-55b5501755df.png)
> c->mqtt_network在network_release里面被清零了，所以不用释放，直接屏蔽 platform_memory_free(c->mqtt_network)，添加c->mqtt_write_buf和c->mqtt_read_buf内存释放，就可以了

openwrt现在不搞了吗？

**Comment by ganggangl** [comment]
> ![image](https://user-images.githubusercontent.com/6436021/92376088-a2ca9400-f134-11ea-8a59-55b5501755df.png)
> c->mqtt_network在network_release里面被清零了，所以不用释放，直接屏蔽 platform_memory_free(c->mqtt_network)，添加c->mqtt_write_buf和c->mqtt_read_buf内存释放，就可以了

@Torchwoods openwrt现在不搞了吗？

**Comment by jiejieTop** [comment]
感谢各位的issue，现在已解决。
