### ISSUE TITLE
mqtt_set_write_buf_size只改了size，没有重新分配buf

### ISSUE THREAD

**Issue by hl10105210** [jiejieTop/mqttclient#17]
RT

**Comment by jiejieTop** [comment]
已修复 , 感谢反馈 
详细见[https://github.com/jiejieTop/mqttclient/commit/2def6b72013c73a45fc5042a8b8e5e9903af7bb7](https://github.com/jiejieTop/mqttclient/commit/2def6b72013c73a45fc5042a8b8e5e9903af7bb7)
