### ISSUE TITLE
无法应用TLS层

### ISSUE THREAD

**Issue by qinfeng2002** [jiejieTop/mqttclient#18]
network.c中

int network_connect(network_t *n)
{
#ifndef MQTT_NETWORK_TYPE_NO_TLS
    if (n->channel)
        return nettype_tls_connect(n);
#endif
    return nettype_tcp_connect(n);

}
n->channel要大于0才能进入tls

network_init中
#ifndef MQTT_NETWORK_TYPE_NO_TLS
    n->channel = 0;

    if (NULL != ca) {
        network_set_ca(n, ca);
    }
#endif

请确认一下，这里是不是有问题，如果设置为0后边就无法调用tls了

**Comment by jiejieTop** [comment]
在network_set_ca中会设置channel的值的,需要根据是否有ca去选择tls或者tcp通道

**Comment by qinfeng2002** [comment]
收到了，现在碰到一个问题，一个云平台用的是单向认证，没有ca证书，这种情况下，但是握手交换秘钥过程是有的，这种情况下，程序满足不了

**Comment by jiejieTop** [comment]
> 收到了，现在碰到一个问题，一个云平台用的是单向认证，没有ca证书，这种情况下，但是握手交换秘钥过程是有的，这种情况下，程序满足不了

这种没有双向认证的代码,您可以自己去修改一下哈~没关系的,主要是满足您的应用即可
