### ISSUE TITLE
mqtt服务器在云端，利用Linux版本mqttclient交叉编译库构建的应用代码，由于网络不稳定（ping服务器有时会超时），导致程序直接挂掉

### ISSUE THREAD

**Issue by wangluolaowu** [jiejieTop/mqttclient#20]
大咖你好， 我利用Linux最新版本mqttclient源码交叉编译的库，在此基础上做应用开发（主要功能是定时发布消息，订阅消息），做了两个测试(启动应用程序的同时，一直另开一个窗口ping服务器)：1.mqtt服务器部署在局域网，网络很稳定（ping延时<1ms）,应用程序运行很稳定；  2.mqtt服务器部署在云端，网络不稳定(ping延时在40ms左右，有时会超时连接)，遇到两个问题：a.当应用程序启动时，有时候会出现构建mqtt_yield_thread失败的情况；b.程序正常启动，mqtt_yield_thread构建成功，当网络稳定时，可以正常发布消息，但当网络不稳定时，特别是当ping服务器超时情况出现时，如果此时要发布消息，那么应用程序就会挂掉；  
我看mqttclient程序readme，有掉线重连机制，但为什么会出现程序运行时挂掉的情况呢？
刚接触mqttclient，请多指教！问题大致出在哪？修改大致思路是？
我想达到的效果是：1.程序初启动时，即使mqtt服务器连接不上，mqtt_yield_thread内部线程也要正常启动，然后通过掉线重连机制，定时重连服务器，直到连上为止； 2.在复杂不稳定网络环境下，不会导致程序异常退出。

**Comment by wangluolaowu** [comment]
应用程序关于mqttclient的配置，除了服务器地址，用户名，密码这些必须的外，其它都是默认配置（我是参考例程写的）；

**Comment by jiejieTop** [comment]
首先,非常感谢您对这个项目的认可,也非常感谢提出这个测试的问题,

不知道这个issue是否对您有帮助,可以先看看[https://github.com/jiejieTop/mqttclient/issues/19](https://github.com/jiejieTop/mqttclient/issues/19)

感觉现象有点像,可能是由于网络的原因,导致服务器将客户端主动断开了,

如果是服务端主动发起关闭，此时四次挥手的顺序会颠倒。那么此时客户端再向服务端发送数据时，**根据TCP协议的规定，认为它是一个异常终止连接，客户端将会收到一个RST复位响应(而不是ACK响应)，如果客户端再次向服务端发送数据，系统将会发送一个SIGPIPE信号给客户端进程，告诉客户端进程该连接已关闭，不要再写了。系统给SIGPIPE信号的默认处理是直接终止收到该信号的进程，所以此时客户端进程会被极不情愿地终止。**
如果不希望客户端进程被终止，可以自定义一个该信号处理的函数，通过调用函数signal(SIGPIPE, handler)实现对信号的处理，其中handler就是可以自定义的函数。
所以说当服务端主动关闭，客户端继续写两次将会导致客户端进程被终止(服务端并不能接收)，客户端不能向服务器写入数据。

进程会终止，是因为服务器主动close后，客户端还往服务器写数据。

在你的测试代码里面去添加这些测试代码，你就能捕获到异常情况了：

```c
#include <signal.h>

....


void handler(int h)
{
    printf("signal handler\n");
}

....

int main(void)
{

....

    signal(SIGPIPE, handler);

....

}

....


```

**Comment by wangluolaowu** [comment]
谢谢大咖的回复，根据你的提示，在测试例程中加上signal(SIGPIPE, handler);捕获到异常情况了； 从打印信息来看，此时mqtt_get_client_state状态为仍为CLIENT_STATE_CONNECTED，程序就会进入到这个地方：
`        /* mqtt connected, handle mqtt packet */
        rc = mqtt_packet_handle(c, &timer);

        if (rc >= 0) {
            /* scan ack list, destroy ack handler that have timed out or resend them */
            mqtt_ack_list_scan(c, 1);`

已经确认mqtt服务端没有做什么特殊配置，基本上都是默认参数；我现在的问题是：接下来怎么处理这种情况，怎样才能重新连上服务器，正常发布消息？

**Comment by wangluolaowu** [comment]
我现在的处理方式是，当捕获到该异常情况后，在void handler(int h)函数中增加int mqtt_try_reconnect(mqtt_client_t* c)；利用该函数进行重连，但一直打印的信息是：[W] >> ../mqttclient/mqttclient.c:603 mqtt_try_do_reconnect()... mqtt try connect result is -0x0004

**Comment by wangluolaowu** [comment]
谢谢大咖的回复；我目前的解决办法，捕获到SIGPIPE信号后， 先释放掉socket连接，然后通过mqtt_set_client_state（）设置client状态为：CLIENT_STATE_DISCONNECTED；
`	/*must realse the socket file descriptor*/
	network_release(client->mqtt_network);

	/* record too much retransmitted data, may be disconnected, need to reconnect */
	mqtt_set_client_state(client, CLIENT_STATE_DISCONNECTED);`
