### ISSUE TITLE
订阅时单独设置的handle收不到消息

### ISSUE THREAD

**Issue by IHIDCHAOS** [jiejieTop/mqttclient#27]
单独设置handle无效，设置全局的handle才能收到订阅的消息。
抓包看报文确实下发到了设备。请教一下代码哪里出了问题，谢谢！
```
void mqtt_message_handle(void* client, message_data_t* msg)
{
    //始终进不来
    printf("message comes...\n");
    char *buf = msg->message->payload;
    if (strstr(msg->topic_name, "command_resp")) {
        //
    }
}

static int get_token(mqtt_client_t *client){
    mqtt_set_host(client, server);
    mqtt_set_port(client, he_wu_port);
    mqtt_set_user_name(client, imei);
    mqtt_set_password(client, pid);
    mqtt_set_client_id(client, imei);
    mqtt_set_clean_session(client, true);

    mqtt_connect(client);

    char pub_topic[256] = {0};
    char sub_topic[256] = {0};
    //device/products/382381/devices/355750075160144/command
    //device/products/382381/devices/355750075160144/command_resp
    sprintf(pub_topic, "device/products/%s/devices/%s/command",pid, imei);
    sprintf(sub_topic, "device/products/%s/devices/%s/command_resp",pid, imei);
    printf("pub_topic:%s\n",pub_topic);
    printf("sub_topic:%s\n",sub_topic);
    //这里设置了handle
    mqtt_subscribe(client, sub_topic, QOS0, mqtt_message_handle);
    return he_wu_publish(client,pub_topic);
}

int main(void)
{
    mqtt_client_t *client = NULL;
    printf("welcome to mqtt client...\n");
    client = mqtt_lease();
//    mqtt_set_interceptor_handler(client,mqtt_message_handle);
    get_token(client);

    sprintf(creq_topic, "$sys/%s/%s/creq/+", pid, imei);
    sprintf(crsp_topic, "$sys/%s/%s/crsp/", pid, imei);
    sprintf(sqdata_topic, "$sys/%s/%s/sqdata", pid, imei);

    while (1) {}

}
```
![image](https://user-images.githubusercontent.com/20263334/103081631-4c199500-4613-11eb-87c2-4e398c8fb3b2.png)

**Comment by jiejieTop** [comment]
可以尝试设置一下拦截器,捕获一下是否能收到topic:

```c
mqtt_set_interceptor_handler(client, mqtt_message_handle);     // set interceptor handler
```

**Comment by jiejieTop** [comment]
另外您说的

`单独设置handle无效，设置全局的handle才能收到订阅的消息。`

单独设置指的是什么?全局设置的指的是什么

**Comment by IHIDCHAOS** [comment]
> 可以尝试设置一下拦截器,捕获一下是否能收到topic:
> 
> ```c
> mqtt_set_interceptor_handler(client, mqtt_message_handle);     // set interceptor handler
> ```

在main函数里设置拦截器是可以收到的。

> 另外您说的
> 
> `单独设置handle无效，设置全局的handle才能收到订阅的消息。`
> 
> 单独设置指的是什么?全局设置的指的是什么

单独设置指为某个具体的topic（如代码中的    `mqtt_subscribe(client, sub_topic, QOS0, mqtt_message_handle);`）设置handle。

全局的handle指的是使用拦截器的方式。

可能我的说法比较怪异，不好意思。

**Comment by IHIDCHAOS** [comment]
不好意思，我发现这并不是拦截器的问题。

在发布消息后等待1秒即可解决，但是我不太明白其中的原因，您可以讲解一下吗？非常感谢！
```
    mqtt_subscribe(client, sub_topic, QOS0, mqtt_message_handle);
    he_wu_publish(client,pub_topic);
    mqtt_sleep_ms(1000);
```

**Comment by jiejieTop** [comment]
应该是订阅还未得到回应（数据传输需要时间？）你可以在初始化的时候就订阅这个topic，然后在需要的时候publish。

**Comment by IHIDCHAOS** [comment]
请问自动或手动重连后如何设置自动重新订阅topic？没有看到相关的API提供。

**Comment by jiejieTop** [comment]
> 请问自动或手动重连后如何设置自动重新订阅topic？没有看到相关的API提供。

没有手动重连的API,因为用户并不能保证知道是否断开了,但有自动重连的操作, 自动重连会自动重新订阅topic.

**Comment by narwallt** [comment]
char pub_topic[256] = {0};
    char sub_topic[256] = {0};
    //device/products/382381/devices/355750075160144/command
    //device/products/382381/devices/355750075160144/command_resp
    sprintf(pub_topic, "device/products/%s/devices/%s/command",pid, imei);
    sprintf(sub_topic, "device/products/%s/devices/%s/command_resp",pid, imei);
    printf("pub_topic:%s\n",pub_topic);
    printf("sub_topic:%s\n",sub_topic);

---------->  不能用局部变量设置topic，需要全局或者静态变量。这个mqtt库并不会另外保存topic。我自己也遇到过类似问题，改成全局变量后，就ok了
