### ISSUE TITLE
Combine libhv to provide asynchronous mqtt client

### ISSUE THREAD

**Issue by ithewei** [jiejieTop/mqttclient#28]
你好，
我是[libhv](https://github.com/ithewei/libhv)的作者，简单介绍下，libhv是一个跨平台的类似libevent的网络库。
最近在寻找跨平台的mqtt客户端实现，看到你这个库，感觉非常的优秀，不亚于mosquitto。

计划适配到libhv来提供异步的mqtt客户端库，以完善libhv的网络协议生态，计划见[PLAN.md](https://github.com/ithewei/libhv/blob/master/docs/PLAN.md)
目前已实现http client/server，适配了hiredis(见https://github.com/redis/hiredis/pull/904)
websocket在开发中，mqtt不知道你是否有兴趣贡献或提供帮助。

**Comment by jiejieTop** [comment]
哇，久仰大神名号，我们其实还是微信好友的哈～，其实我自己也一直有在使用libuv，如果能跟您这边与合作的话，我确实很想尝试一下，但可能时间有限，还请不要责怪进度太慢哈。

ps：顺道问一句，是否有打算提供非异步的功能呢。

**Comment by ithewei** [comment]
这里的异步应该是做成类似mosquitto在一个内部线程运行一个事件循环，触发订阅回调函数。
 大家都有工作，进度没有期限，能得大佬贡献，感激不尽。

**Comment by ithewei** [comment]
libhv里已实现异步MQTT客户端，见https://github.com/ithewei/libhv/blob/master/mqtt/mqtt_client.h
我将关闭此issue，再次感谢！
