### ISSUE TITLE
小bug

### ISSUE THREAD

**Issue by YuanPeiDong** [jiejieTop/mqttclient#29]
文件plooc_class.h第43行
#if (!defined(__STDC_VERSION__) || __STDC_VERSION__ < 199901L) && !defined(__cplusplus)
多了！，应该为
#if (defined(__STDC_VERSION__) || __STDC_VERSION__ < 199901L) && !defined(__cplusplus)

**Comment by GorgonMeducer** [comment]
你好，我是PLOOC的作者，这里没有多“！”
上述宏的本意就是：
如果没有定义 STDC_VERSION（大部分只支持C90编译器不会定义这个宏）；或者在定义了STDC_VERSION的情况下，版本号低于C99（199901L）。总的来说，这个判断的意思就是说，如果你不支持C99，而支持C90……

希望能解释你的疑惑。
