### ISSUE TITLE
Demo test result

### ISSUE THREAD

**Issue by sg0993** [jiejieTop/mqttclient#3]
I have build and test this sample,when run the ~/mqtt/mqttclient/build/bin/mqtt-client,
     only print  "welcome to mqttclient test...".
     I found that the code run in function platform_nettype_tls_connect(),
          if (0 != (rc = mbedtls_net_connect(&(nettype_tls_params->socket_fd),      n->network_params.addr,n->network_params.port, MBEDTLS_NET_PROTO_TCP))) 
    goto exit;
  
    It can't run to next line,and tcpdump found TCP has Retransmission.
     I want to run this demo to confirm it ,and then I can transported to out platform.
     Would help to check how to run this demo normally?

     Thanks!

Regards,
Ellen

**Comment by jiejieTop** [comment]
good evening, I understand your problem,please check that the **IP address** and **port** are configured correctly. If you have the conditions, you can use `tcpdump` in the server to get the packets and see if you receive a connection request from the client.

**Comment by jiejieTop** [comment]
you can use my server for testing, it is currently open.
