### ISSUE TITLE
关于编译成动态库libmqttclient.so的一个问题请教下up

### ISSUE THREAD

**Issue by piaotq** [jiejieTop/mqttclient#30]
我在./test/mqtt_config.h中，将#define     MQTT_NETWORK_TYPE_NO_TLS 打开，相当于配置了不带tls的通信方式，那么我编译库文件的时候，是不是应该比我打开tls通信方式编译得到的库文件要小很多呢？ 我目前编译后发现两者是几乎一样大的，请问我的理解是有错误么？

**Comment by szullc** [comment]
hi 朋友，

我觉得你可以检索下源码，看下MQTT_NETWORK_TYPE_NO_TLS这个宏下面包了多少代码？
有可能只是功能编译开关，并没有完全把不相干的代码都不参与编译。
另外，你说的编译出了的库大小变化不大；如果链接成elf文件或bin文件呢，前后大小差异大吗？

**Comment by piaotq** [comment]
> hi 朋友， 我觉得你可以检索下源码，看下MQTT_NETWORK_TYPE_NO_TLS这个宏下面包了多少代码？ 有可能只是功能编译开关，并没有完全把不相干的代码都不参与编译。 另外，你说的编译出了的库大小变化不大；如果链接成elf文件或bin文件呢，前后大小差异大吗？

链接成bin前后的差异是很大的，所以我才会觉得so理应变小才对，如果有引导方向或在理解也请不吝赐教，谢谢啦。
