### ISSUE TITLE
用c++ 调用这个库会报错

### ISSUE THREAD

**Issue by hanhy2416** [jiejieTop/mqttclient#38]
error: types may not be defined in ‘sizeof’ expressions
 #   define PLOOC_SIZEOF_STRUCT(...)        sizeof(struct {__VA_ARGS__})

**Comment by jiejieTop** [comment]
切换到stable分支

**Comment by hanhy2416** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        我试试，谢谢啦
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
    
        签名由网易邮箱大师定制
    
 

    在2021年6月15日 ***@***.***> 写道： 




切换到stable分支
