### ISSUE TITLE
mem leak

### ISSUE THREAD

**Issue by BravoJH88** [jiejieTop/mqttclient#4]
mqtt_client_t write_buf is mem leak

**Comment by jiejieTop** [comment]
oh, my carelessness led to a memory leak, which is now fixed!
thanks~

**Comment by jiejieTop** [comment]
@BravoJH88
already fixed:[https://github.com/jiejieTop/mqttclient/commit/f624f0897514d5cf3bbeaedd0c19075a2dcaba96](https://github.com/jiejieTop/mqttclient/commit/f624f0897514d5cf3bbeaedd0c19075a2dcaba96)
