### ISSUE TITLE
payload does not work with binary data

### ISSUE THREAD

**Issue by sunbelt56** [jiejieTop/mqttclient#40]
I'm using one of the examples in test, running one version on a Linux desktop and the other on a Raspberry Pi and the mqtt_publish in the Rpi sends a selected file to the mqtt_subscribe on the Linux desktop. If I select a text file, it works just fine. If I select a binary file, like a jpg, it comes over as all zeros. I'm going to post a boiled-down version of the code soon.

**Comment by sunbelt56** [comment]
my repo is:
[https://github.com/sunbelt56/mqtt](url)

**Comment by jiejieTop** [comment]
generally speaking, there is not much difference between string and binary data, but the way of displaying (printing) is different, you can use dump to print them(jpg / png)
