### ISSUE TITLE
mqttclient.h 头文件引入之后，宏定义错误问题

### ISSUE THREAD

**Issue by vimsky** [jiejieTop/mqttclient#43]
mqttclient.h 头文件引入之后之后，编译项目，出现plooc_class.h头文件中， error: types may not be defined in ‘sizeof’ expressions
  173 | #   define PLOOC_SIZEOF_STRUCT(...)        sizeof(struct {__VA_ARGS__}) 错误，如何处理
      |                                                          ^

**Comment by jiejieTop** [comment]
如果不使用plooc的话（如果是c++代码的话），可以切换到stable分支
或者定义一个宏定义 `__OOC_CPP__ `，这样子与cpp共存

**Comment by vimsky** [comment]
好的，我试试
