### ISSUE TITLE
在项目中#include “mqttclient.h"后，编译错误

### ISSUE THREAD

**Issue by yuanmartin** [jiejieTop/mqttclient#49]
arm-linux-gnueabihf-下编译报错：plooc_class.h:173:58: 错误： types may not be defined in ‘sizeof’ expressions  #   define PLOOC_SIZEOF_STRUCT(...)        sizeof(struct {__VA_ARGS__})

**Comment by jiejieTop** [comment]
切换到stable分支

**Comment by yuanmartin** [comment]
thank you very much
