### ISSUE TITLE
关于CA证书连接问题

### ISSUE THREAD

**Issue by li19960328** [jiejieTop/mqttclient#52]
您好，我看您给出的test/emqx/test_ca.c当中有两个ca证书，为啥要使用两个ca证书连接呢？我使用您给的例程跑起来过大概一分钟报错0x0008，无法连接。我使用自己的账号加mqtt.fx连接，ca证书只有一份，其中配置用户名、密码、ca.crt，协议为SSLv3，即可连接。但是当在程序中使用这一份ca证书连接时却无法连接，大约1秒钟就报错network/nettype_tls.c:30 返回错误0x0004。

**Comment by fanucwj** [comment]
请问这个问题解决了吗？
