### ISSUE TITLE
mqtt_keep_alive函数有BUG

### ISSUE THREAD

**Issue by qkaibo** [jiejieTop/mqttclient#53]
int mqtt_keep_alive(mqtt_client_t* c)
{
    int rc = MQTT_SUCCESS_ERROR;
    
    rc = mqtt_is_connected(c);
    if (MQTT_SUCCESS_ERROR != rc)
        RETURN_ERROR(rc);

    if (platform_timer_is_expired(&c->mqtt_last_sent) || platform_timer_is_expired(&c->mqtt_last_received)) {
        if (c->mqtt_ping_outstanding) {
            MQTT_LOG_W("%s:%d %s()... ping outstanding", __FILE__, __LINE__, __FUNCTION__);
            /*must realse the socket file descriptor zhaoshimin 20200629*/
            network_release(c->mqtt_network);
            
            mqtt_set_client_state(c, CLIENT_STATE_DISCONNECTED);
            rc = MQTT_NOT_CONNECT_ERROR; /* PINGRESP not received in keepalive interval */
        } else {
            platform_timer_t timer;
            int len = MQTTSerialize_pingreq(c->mqtt_write_buf, c->mqtt_write_buf_size);
            if (len > 0 && (rc = mqtt_send_packet(c, len, &timer)) == MQTT_SUCCESS_ERROR) // send the ping packet
                c->mqtt_ping_outstanding++;
        }
    }

以上函数中
 if (len > 0 && (rc = mqtt_send_packet(c, len, &timer)) == MQTT_SUCCESS_ERROR) // send the ping packet
                c->mqtt_ping_outstanding++;

这里如果mqtt_send_packet 返回失败， 则 c->mqtt_ping_outstanding就一直保持是0 所以就一直不会断线
 全局设置网络状态的地方 好像还有一个 PUBLISH时候 但是如果一直不publish那  就是keep alive这里发送失败 也不会认为掉线

**Comment by jiejieTop** [comment]
已修复，感谢您的提交~
