### ISSUE TITLE
关于调用mqtt_release出现fail的问题

### ISSUE THREAD

**Issue by Yangyuanxin** [jiejieTop/mqttclient#58]
杰神，我在写测试用例的时候需要在最终程序退出时调用mqtt_release来释放已经分配的内存，当我调用这句话的时候，走到了这个分支里：
```
    /* wait for the clean session to complete */
    while ((CLIENT_STATE_INVALID != mqtt_get_client_state(c))) {
        // platform_timer_usleep(1000);            // 1ms avoid compiler optimization.
        if (platform_timer_is_expired(&timer)) {
            MQTT_LOG_E("%s:%d %s()... mqtt release failed...", __FILE__, __LINE__, __FUNCTION__);
            RETURN_ERROR(MQTT_FAILED_ERROR)
        }    
    }
```
这也就意味着我的测试用例在之前调用mqtt_lease等接口所申请的内存并没有被释放。我在你提供的example样例里没有看到有关于它的使用方法，这里如果正确使用的话该怎么调用它才能成功呢？

**Comment by Yangyuanxin** [comment]
我还发现了一个问题点，由于创建线程的函数里是申请了内存的：
platform_thread_t *platform_thread_init( const char *name,
                                        void (*entry)(void *),
                                        void * const param,
                                        unsigned int stack_size,
                                        unsigned int priority,
                                        unsigned int tick)
{
    int res;
    platform_thread_t *thread;
    void *(*thread_entry) (void *);

    thread_entry = (void *(*)(void*))entry;
    thread = platform_memory_alloc(sizeof(platform_thread_t));
    
    res = pthread_create(&thread->thread, NULL, thread_entry, param);
    if(res != 0) {
        platform_memory_free(thread);
    }

    thread->mutex = (pthread_mutex_t)PTHREAD_MUTEX_INITIALIZER;
    thread->cond = (pthread_cond_t)PTHREAD_COND_INITIALIZER;

    return thread;
}

**Comment by frank010180** [comment]
我也有同樣的問題
是否有解
未能清除session  也無法釋放client的內容
導致我無法重新連線

**Comment by ctbsea** [comment]
> 杰神，我在写测试用例的时候需要在最终程序退出时调用mqtt_release来释放已经分配的内存，当我调用这句话的时候，走到了这个分支里：
> 
> ```
>     /* wait for the clean session to complete */
>     while ((CLIENT_STATE_INVALID != mqtt_get_client_state(c))) {
>         // platform_timer_usleep(1000);            // 1ms avoid compiler optimization.
>         if (platform_timer_is_expired(&timer)) {
>             MQTT_LOG_E("%s:%d %s()... mqtt release failed...", __FILE__, __LINE__, __FUNCTION__);
>             RETURN_ERROR(MQTT_FAILED_ERROR)
>         }    
>     }
> ```
> 
> 这也就意味着我的测试用例在之前调用mqtt_lease等接口所申请的内存并没有被释放。我在你提供的example样例里没有看到有关于它的使用方法，这里如果正确使用的话该怎么调用它才能成功呢？

同问
