### ISSUE TITLE
您好，我遇到了一个编译的错误

### ISSUE THREAD

**Issue by wangxiaoer3924** [jiejieTop/mqttclient#76]
您好，当我编译代码的时候提示下面的问题，我尝试搜了一下，但是因为确实对cmakelist理解的不深，所以不知道应该如何修改
RegularExpression::compile(): Nested *?+.
RegularExpression::compile(): Error in compile.
CMake Error at cmake/install.cmake:5 (string):
  string sub-command REGEX, mode REPLACE failed to compile regex
  "/home/dixn/data/src/git-open/c++/mqtt/mqttclient/".
Call Stack (most recent call first):
  CMakeLists.txt:57 (install_project)

这个正则我不知道应该如何处理
        string(REGEX REPLACE "${CMAKE_CURRENT_SOURCE_DIR}/" "" dir ${dir})

我把这个install_project安装函数注释掉以后可以编译通过，但是我编译动态库的时候提示缺少文件

cp: 无法获取'/home/dixn/data/src/git-open/c++/mqtt/mqttclient/test/*.h' 的文件状态(stat): 没有那个文件或目录

deb安装是没有问题的，但是我想亲自编译一下然后将头文件和库文件复制到项目目录里面使用

而且我发现不是我一个人遇到这个问题，之前也有人提问，但是最后没有回复了

**Comment by jiejieTop** [comment]
你用了c++这个路径，正则表达式不通过
