### ISSUE TITLE
执行build.sh出现问题

### ISSUE THREAD

**Issue by hisili1** [jiejieTop/mqttclient#79]
![图片](https://user-images.githubusercontent.com/128700151/230713397-b4d6c79b-1389-4092-b9c5-a183198a494b.png)

**Comment by hisili1** [comment]
这是什么问题呢

**Comment by jiejieTop** [comment]
cmakelist的问题，这需要先安装mqttclient，我现在更新了，你重新编译一下吧

**Comment by hisili1** [comment]
执行完./build.sh之后好像没有生成 build/bin/emqx这个文件
![图片](https://user-images.githubusercontent.com/128700151/233236970-c056496d-bc70-4263-96be-62dfcd2c7d59.png)
