### ISSUE TITLE
谢谢大牛牛啊

### ISSUE THREAD

**Issue by skyformat99** [jiejieTop/mqttclient#8]
好棒棒啊；
谢谢大牛牛；
你这个库必须依赖paho mqtt啊？

**Comment by jiejieTop** [comment]
本来就是它作为mqtt封包的~这个库写的非常好，而且非常小，你看占用的资源就知道了~

**Comment by skyformat99** [comment]
> 本来就是它作为mqtt封包的，这个库写的非常好，而且非常小，你看占用的资源就知道了。

现在是直接源码引用的吧？
就是说，直接把这个库文件都引入就自然包含paho了吧。这样就好。
